version: '3.9'

services:
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-mindvibe_db}
      POSTGRES_USER: ${POSTGRES_USER:-mindvibe_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-your_strong_password}
    ports:
      - "5433:5432"
    restart: always

  web:
    build: .
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8000:8000"
    environment:
      SECRET_KEY: ${SECRET_KEY:-your_default_django_secret_key}
      DEBUG: ${DEBUG:-0}
      DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS:-localhost,127.0.0.1}
      DATABASE_URL: ${DATABASE_URL:-postgres://mindvibe_user:your_strong_password@db:5432/mindvibe_db}
    depends_on:
      - db
    restart: always

volumes:
  postgres_data:
  static_volume:
  media_volume:
